### ISSUE TITLE
Add inclusion/exclusion filters with decent defaults

### ISSUE THREAD

**Issue by GuiSim** [coveo/fmt-maven-plugin#2]
Currently the plugin attempts to format ALL files in the source folders. This can lead to the plugin attempting to format `.DS_Store` files and other unwanted files.

Since this is a Java formatter, I suspect that an inclusion filter with the default value of `*.java` would be a pretty decent starting point.

**Comment by GuiSim** [comment]
Note that the only effect that this has is that it pollutes the maven build logs with warnings and stacktraces.

We could probably only print the stacktrace in verbose while we're at it.

**Comment by malaporte** [comment]
Fixed by #4.
