### ISSUE TITLE
Feature Request: Support for `aosp` mode

### ISSUE THREAD

**Issue by bryanschofield** [coveo/fmt-maven-plugin#26]
The Google Formatter supports an alternate style that aligns with Android Open Source Project style.
While not well documented on the formatter's Github page, you can see it is supported in the command line options. AOSP mode is also supported as an option in the IntelliJ plugin.

```
Usage: google-java-format [options] file(s)

Options:
  ... 
  --aosp, -aosp, -a
    Use AOSP style instead of Google Style (4-space indentation).
 ...
```

I propose adding a configuration option to this plugin that allows the style to be set.
- The configuration gains a `style` option
   - `google` shall be the default and matches the current behavior.
   - `aosp` shall enable `AOSP` mode .
   - Any other value is considered a failure.
- The style option is available via system property `-Dstyle=<google|aosp>`

```
<configuration>
  <style>google</style>
</configuration>
```

See also: https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/java/JavaFormatterOptions.java#L40

**Comment by bryanschofield** [comment]
Here is a PR: https://github.com/coveo/fmt-maven-plugin/pull/25

**Comment by aaime** [comment]
The pull request has been merged, so I guess this issue could be closed?
