### ISSUE TITLE
Update to google-java-format 1.6

### ISSUE THREAD

**Issue by tbroyer** [coveo/fmt-maven-plugin#33]
1.6 was released last week: https://github.com/google/google-java-format/releases/tag/google-java-format-1.6

**Comment by GuiSim** [comment]
Hi Thomas! Thanks for the heads up, would you be willing to submit a PR with the updated dependency?

If you can't, I will try to look at it but it will take a while because I am currently traveling.

**Comment by tbroyer** [comment]
Here you go! → #34 :wink:
