### ISSUE TITLE
Lambda inconsistency

### ISSUE THREAD

**Issue by jeffzoch** [coveo/fmt-maven-plugin#46]
In intellij w/ google java format xml imported we have the following formatted code:
```
 public void generateTickets() {
    jobsConfiguration
        .getJobs()
        .stream()
        .filter(Job::isEnabled)
        .forEach(j -> ticketGenerator.generateTickets(j, windowHours));
  }
```
This is really nice because it also shows intellij type hints on each line. With this plugin though we get the following:
```
  public void generateTickets() {
    jobsConfiguration.getJobs().stream()
        .filter(Job::isEnabled)
        .forEach(j -> ticketGenerator.generateTickets(j, windowHours));
  }
```
I think both are actually valid since g-j-f doesnt specify how to line wrap but it would be nice if you could support the former way since type hints are better and imo is clearer.

**Comment by Stephan202** [comment]
The latter format is now an (unconfigurable) feature of GJF version [1.7](https://github.com/google/google-java-format/releases/tag/google-java-format-1.7). One thing you could do is configure an explicit plugin dependency on version 1.6. (But longer term that doesn't sound like a good plan.)

Consider leaving feedback on google/google-java-format#341.

**Comment by malaporte** [comment]
We cannot address issue about the formatting itself.
