### ISSUE TITLE
Enumerated Lambda

### ISSUE THREAD

**Issue by ap6us** [coveo/fmt-maven-plugin#49]
Within a multi-line lambda enum declaration, the formatter is inserting a line break after the parent following the constant identifier.   

From this source, which passes checkstyle:
```

  CLASS_FORMATTER((s, r, a) -> {
    return (r.getSourceClassName() != null) //4 space indent
         ? s.append(INDENT_SPACES).append(r.getSourceClassName())
         : (r.getLoggerName() != null) ? s.append(INDENT_SPACES).append(r.getLoggerName()) : s;
   }),
```

formatter renders:
```
  CLASS_FORMATTER(
      (s, r, a) -> { 
        return (r.getSourceClassName() != null)
            ? s.append(INDENT_SPACES).append(r.getSourceClassName())
            : (r.getLoggerName() != null) ? s.append(INDENT_SPACES).append(r.getLoggerName()) : s;
      }),
```

Checkstyle:
>  Warning 	indentation 	Indentation 	'lambda arguments' has incorrect indentation level 6, expected level should be 10.
>  Warning 	indentation 	Indentation 	'block' child has incorrect indentation level 8, expected level should be 12.

Checkstyle 8.18's suggestion to increase the indent is not consistent with Google Style and does not cause it to pass.  

Google Style Guide 4.8.1 has nothing to say about enumerations that have field members, but when discussing body declarations it has the body's opening brace on the same line as the as the identifier:

```
private enum Answer {
  YES {
    @Override public String toString() {
      return "yes";
    }
  },

```

Formatter doesn't seem to be breaking any Google rules, although I understand one its goals is to pass checkstyle as published.  Should this be handled here or in checkstyle?   My preference would be to for formatter to accept the unbroken declaration because it puts the parameters on the same line as the constant identifier, and because the closing paren + brace is flush with the block containing the declaration, signaling that the following declaration is not part of it.

**Comment by malaporte** [comment]
All the formatting this plugin done is performed by the Google Formatter - this is just a wrapper to get it to work in Maven. If you have issues regarding the actual formatter, I suggest you head over to their own repo (https://github.com/google/google-java-format). Thanks!
