### ISSUE TITLE
Enable passing a list of files to format

### ISSUE THREAD

**Issue by kg-currenxie** [coveo/fmt-maven-plugin#55]
We're using git hooks to format files automatically before committing.
We're using [Husky](https://github.com/typicode/husky) and [lint-staged](https://github.com/okonet/lint-staged) for this. Here's how its configuration looks like:

```
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
    }
  },
  "lint-staged": {
    "src/main/java/**/*.java": [
      "mvn fmt:format",
      "git add"
    ]
  },
```

However, it just passes the about-to-be-commited files as a list of arguments, like so:

`mvn fmt:format /Users/x/SOME_FOLDER/SOME_FILE.java  /Users/x/SOME_FOLDER/ANOTHER_FILE.java`

Would be cool if this plugin would support this way of passing arguments :P Thx.

**Comment by malaporte** [comment]
This plugin is really designed to run as part of a Maven build, and format all the files in one go. If you want to target individual files, you should rather invoke the Google Formatter directly (there are samples here: https://github.com/google/google-java-format)
