### ISSUE TITLE
Validation mode.

### ISSUE THREAD

**Issue by JLLeitschuh** [coveo/fmt-maven-plugin#8]
It would be nice if there was some sort of validation mode that would diff the output of this plugin against the files to see if there were changes.

This would be useful from a CI perspective because you want it to fail if the developer hasn't run the reformat on their code before pushing.

**Comment by GuiSim** [comment]
Pull requests are welcome!

It should be pretty easy to add, check out https://github.com/coveo/fmt-maven-plugin/pull/7 which might give you a good starting point.

**Comment by malaporte** [comment]
Feature was contribued by @olim7t - thanks for this! Closing this issue.

**Comment by tbroyer** [comment]
This should have been added as a new `check` goal bound to the `verify` phase to make it easy to have it run as part of the build, and manually run `mvn fmt:format` when needed.

(btw, it's nonsensical to bind the `format` goal to a phase; modifying sources should only ever be done by a direct invocation of a goal, sources are supposed to be immutable in Maven –this is why all outputs happen in the `target/` folder, compared to e.g. the default behavior of javac to output `.class` files next to their `.java` sources)

Currently, I'm configuring my projects using the following snippet:
```xml
      <plugin>
        <groupId>com.coveo</groupId>
        <artifactId>fmt-maven-plugin</artifactId>
        <version>1.5.0</version>
        <executions>
          <execution>
            <phase>verify</phase>
            <goals>
              <goal>format</goal>
            </goals>
            <configuration>
              <validateOnly>true</validateOnly>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
so I can call `mvn fmt:format` to reformat files on-demand and fail the build in case I somehow forgot (similar to checkstyle and other similar analysis tools).

With a `check` goal, I would instead write:
```xml
      <plugin>
        <groupId>com.coveo</groupId>
        <artifactId>fmt-maven-plugin</artifactId>
        <version>1.5.0</version>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

**Comment by jbduncan** [comment]
@tbroyer I wasn't able to get your example working for my case, but I did manage to find an alternative.

If one adds the following to their pom.xml:
```xml
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.coveo</groupId>
          <artifactId>fmt-maven-plugin</artifactId>
          <version><!-- plugin version goes here --></version>
          <executions>
            <execution>
              <id>check</id>
              <phase>verify</phase>
              <goals>
                <goal>format</goal>
              </goals>
              <configuration>
                <validateOnly>true</validateOnly>
              </configuration>
            </execution>
            <execution>
              <id>format</id>
              <goals>
                <goal>format</goal>
              </goals>
              <configuration>
                <validateOnly>false</validateOnly>
              </configuration>
            </execution>
          </executions>
          <dependencies>
            <dependency>
              <groupId>com.google.googlejavaformat</groupId>
              <artifactId>google-java-format</artifactId>
              <version><!-- google-java-format version goes here --></version>
            </dependency>
          </dependencies>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
```

...then one should be able to run:
- `mvn com.coveo:fmt-maven-plugin:format@check` to _validate_ code against google-java-format
- `mvn com.coveo:fmt-maven-plugin:format@format` to _format_ code with google-java-format

**Comment by tbroyer** [comment]
That's overly verbose for something that could be provided with only minimal configuration.

**Comment by jbduncan** [comment]
@tbroyer Oh? Would you kindly elaborate for me?

**Comment by tbroyer** [comment]
See my proposal at the end of https://github.com/coveo/fmt-maven-plugin/issues/8#issuecomment-297039808

Add a `fmt:check` that works the same as `fmt:format` with `validateOnly=true`, and bind it to the `verify` phase. And then deprecate and eventually remove the `validateOnly` property of `fmt:format`.

My second point, which is entirely distinct actually, is that you never want to format during the build (which your configuration above will do, because `fmt:format` is bound by default to the `process-sources` phase), so `fmt:format` should **not** be bound to any phase, and should further more be marked as `requiresDirectInvocation = true`. A build should not modify its inputs, it should only produce (stable) outputs from the inputs; formatting (modifying the build inputs) should be invoked explicitly outside of the build (with an explicit `mvn fmt:format`)

**Comment by tbroyer** [comment]
BTW, for an example configuration that works for me: https://github.com/tbroyer/jaxrs-utils/blob/44be850e4fda97cb4d2ef05249453cafdcd5f06f/pom.xml#L228-L250
That `<phase>` and `<configuration>` are already too verbose IMO (and the configuration suggested in the README is harmful, if you ask me)

**Comment by jbduncan** [comment]
@tbroyer 

> BTW, for an example configuration that works for me: https://github.com/tbroyer/jaxrs-utils/blob/44be850e4fda97cb4d2ef05249453cafdcd5f06f/pom.xml#L228-L250

Oh, really? When I add it to JUNG's root [pom.xml]() and run `mvn clean fmt:format` from the command-line with Maven 3.5.0, at the root of my local clone of JUNG, it _formats_ the codebase rather than _validates_ it (even if I change the line `<validateOnly>true</validateOnly>` to `<validateOnly>false</validateOnly>`).

In comparison, for my example configuration in https://github.com/coveo/fmt-maven-plugin/issues/8#issuecomment-314911025, `mvn clean fmt:format@check` validates as expected, whereas `mvn clean fmt:format@format` formats as expected.

I'll see if I can create a MCVE to show you.

**Comment by tbroyer** [comment]
Sorry, I should have been clearer. Yes, it works like you describe, and that's exactly how I want it to work: `mvn fmt: format` will format code, and `mvn verify` will, in addition to the build, check that code is properly formatted.

That said, with a `fmt:check` goal, you could easily check for proper formatting using `mvn fmt:check` without building the project.

**Comment by jbduncan** [comment]
@tbroyer Oh cool, thanks for clarifying things further for me!

However I still have problems when I run `mvn clean verify` on my MVCE (which I'll share with you below); it doesn't seem to throw any error at all, even with regards to validation with google-java-format.

Try cloning from https://github.com/jbduncan/fmt-plugin-test. You should find that if you run `git checkout -- .; mvn --version; mvn clean fmt:format`, it will format `src/main/java/com/test/App.java` rather than validate that it's formatted incorrectly; and that if you run `git checkout -- .; mvn --version; mvn clean verify`, it will build successfully, as if `App.java` were already formatted correctly.

Here's what it says for me when I run `git checkout -- .; mvn --version; mvn clean fmt:format`:
```
$ git checkout -- .; mvn --version; mvn clean fmt:format
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T20:39:06+01:00)
Maven home: C:\Users\Jonathan\dev\Tools\Maven\apache-maven-3.5.0
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_121\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building fmt-plugin-test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ fmt-plugin-test ---
[INFO]
[INFO] --- fmt-maven-plugin:1.5.0:format (default-cli) @ fmt-plugin-test ---
[info] Processed 1 files (1 reformatted).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.865 s
[INFO] Finished at: 2017-07-13T16:25:29+01:00
[INFO] Final Memory: 12M/165M
[INFO] ------------------------------------------------------------------------
```

And here's what it says when I run `git checkout -- .; mvn --version; mvn clean verify`:
```
$ git checkout -- .; mvn --version; mvn clean verify
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T20:39:06+01:00)
Maven home: C:\Users\Jonathan\dev\Tools\Maven\apache-maven-3.5.0
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_121\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building fmt-plugin-test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ fmt-plugin-test ---
[INFO] Deleting C:\Users\Jonathan\dev\Java\IntelliJ Projects\fmt-plugin-test\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ fmt-plugin-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Jonathan\dev\Java\IntelliJ Projects\fmt-plugin-test\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ fmt-plugin-test ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\Users\Jonathan\dev\Java\IntelliJ Projects\fmt-plugin-test\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ fmt-plugin-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Jonathan\dev\Java\IntelliJ Projects\fmt-plugin-test\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ fmt-plugin-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ fmt-plugin-test ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ fmt-plugin-test ---
[INFO] Building jar: C:\Users\Jonathan\dev\Java\IntelliJ Projects\fmt-plugin-test\target\fmt-plugin-test-1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.559 s
[INFO] Finished at: 2017-07-13T16:26:26+01:00
[INFO] Final Memory: 16M/171M
[INFO] ------------------------------------------------------------------------
```

**Comment by tbroyer** [comment]
Ha, the snippet should go into build➡plugins, not in pluginManagement ;-)

**Comment by jbduncan** [comment]
Oh! That makes a great deal of sense.

Silly me! :stuck_out_tongue_closed_eyes:

Removing `<pluginManagement>` and `</pluginManagement>` indeed resolves my problem.

Thank you so much @tbroyer!

**Comment by pastjean** [comment]
Great ! i was going to hop in but this seems solves thx @tbroyer

**Comment by tbroyer** [comment]
@pastjean Well, not on my side ;-)

I still strongly believe this `validateOnly` flag is wrong and should be replaced with a `fmt:check` goal bound to the `verify` phase, and `fmt:format` shouldn't be bound to any phase by default.

**Comment by GuiSim** [comment]
I think we could support both mechanism (`validateOnly` flag and `fmt:check` in `verify` phase), at least during a few versions so we avoid breaking things suddenly.

Would you be open to submitting a PR with this feature @tbroyer ?

**Comment by tbroyer** [comment]
Found some free time and got https://github.com/coveo/fmt-maven-plugin/pull/14

**Comment by olim7t** [comment]
FWIW, I agree that having two goals is a cleaner approach. I went with the flag in my initial PR because it was the simplest way to scratch my itch, but if you remove it in a future version it's fine with me.
